### ISSUE TITLE
latest code not in github

### ISSUE THREAD

**Issue by snopoke** [conorbranagan/django-datadog#5]
comparing what is on PyPi to what is in this repo it seems that the latest code hasn't been pushed.

**Comment by patr1ck** [comment]
Seeing as the PyPi version is from @cmheisel, perhaps he'd like to chime in.

**Comment by tom-dalton-fanduel** [comment]
I've cloned this here: https://github.com/tom-dalton-fanduel/django-datadog, and merged a couple of the PRs from here that look useful to me.

My current plan is to fix it up a bit and maintain it going forward, not sure what the best thing will be to do with the pypi package - @conorbranagan what are your thoughts?

**Comment by cmheisel** [comment]
@patr1ck That got submitted by me while I was at Kabbage, this was the fork: https://github.com/KabbageInc/django-datadog 

Happy to transfer that over to @conorbranagan

**Comment by rzinurov** [comment]
First of all, thanks for the library. It saved me a lot of time. I've found a small issue with handling unicode characters in request path. Is there a place where I can contribute with my tiny fix?

**Comment by bittner** [comment]
@cmheisel The README of none of the repositories matches the one on PyPI. It looks like the content has been modified after uploading, though there is no trace of a modification in the package logs on the bottom of the PyPI package page.

Can you explain where the content comes from? Do you recall?

**Comment by cmheisel** [comment]
@bittner IIRC there was an "internal" fork (on the company's git) and the external fork on github.com, I suspect the changes were pushed up from the internal fork.

I can transfer ownership of the PyPi repo to whomever the current maintainer is so the right version gets there.

**Comment by bittner** [comment]
Not sure what an _"internal" fork_ is, but it sounds scary. (And yes, there is no project visible on https://github.com/DataDog, which is specifically related to Django.)

If @conorbranagan is not happy to maintain the package on PyPI maybe @irvined1982 is interested? I'd be happy to co-maintain it and make sure there's a working README on PyPI and a build configuration to run flake8/pylint and tests against all current versions of Python and Django in the repo.

Though, the best solution would be if @DataDog took over ownership and sponsored the development. It's in their best interest to give yet another reason to use DataDog software developed in Python.

**Comment by bittner** [comment]
Note that there are also at least two other packages on PyPI as forks of this repo:

- [ak-django-datadog](https://pypi.python.org/pypi/ak-django-datadog) by @dhilipsiva
- [avk-django-datadog](https://pypi.python.org/pypi/avk-django-datadog) by @avkoval

I think it's worth to join forces, clean things up, and make a one-and-official DataDog package for Django.

**Comment by avkoval** [comment]
:+1:  for the effort. 
My fix for Django 1.10 was mostly mechanical, and I believe not backward compatible with previous Django versions (do we need to support them btw or just release with dependencies of >=1.10?)

**Comment by conorbranagan** [comment]
Hi all,

Sorry for the long, long radio silence. Many things had come up and I never found the time to get around to cleaning up the mess here. I really appreciate the effort to get things moving again and I'd definitely like to standardize around one source for this for everyone's sanity.

I do see the value of maybe having us/datadog maintain it internally but I'm not sure how much bandwidth we have for something like this internally. So I'm reaching out both internally to the integration team and to the most up-to-date and maintained fork (@tom-dalton-fanduel) to figure out a way to move forward on this.

Hopefully I'll have some more news by the end of the week. Thanks again!

**Comment by bittner** [comment]
As mentioned in https://github.com/DataDog/datadogpy/issues/211 it may be a good choice to simply integrate the middleware code into Datadog's [datadog](https://pypi.python.org/pypi/datadog) package.

This may make sense to reduce confusion and enhance simplicity for Datadog customers: Activating [Python integration](https://app.datadoghq.com/account/settings#integrations/python) from the Datadog account settings would do it all; provided specific instructions for installing the middleware are presented on that screen.

We, as the community, can still maintain the Django integration. Provided that Datadog has sufficient proficient resources to handle the few PRs we make, in a timely manner.

**Comment by bittner** [comment]
Note to self: There's also the [`ddtrace` package](http://pypi.datadoghq.com/trace/docs/), which [provides a Django middleware](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/middleware.py) for APM metrics.

**Comment by tom-dalton-fanduel** [comment]
Just to add my 2p. My fork [fdjangodog](https://github.com/tom-dalton-fanduel/fdjangodog) has diverged a fair bit from the original code - it's dropped support for using an api key and only works with sending stats to a local datadog collector. I've also changed the metrics recorded a fair bit. As such I don't think it makes sense for people to migrate to it wholesale, but I'd be very happy to help out integrating the changes I've made back to this project.

I agree that having one 'official' Datadog Django package that everyone contributes to would be better than many fractured packages. Until there's a response on DataDog/datadogpy#211 I think we should assume this package will remain separate, but IMO that's probably a good thing anyway.

**Comment by bittner** [comment]
@conorbranagan @datadog Have you had time to talk about this issue? (during office hours)

**Comment by bittner** [comment]
Any progress here?

**Comment by bittner** [comment]
I've raised a support ticket at Datadog for the issue. (Zendesk ticket number is #98398.)

**Comment by conorbranagan** [comment]
@bittner I'm going to deprecate this repo and point to the [fdjangodog](https://github.com/tom-dalton-fanduel/fdjangodog) repo which is much more up-to-date, uses dogstatsd which is preferred and is still under active development.

Unfortunately I don't have time to maintain this library nor do we have time internally as we'd prefer APM for this anyway.

**Comment by bittner** [comment]
Oh, I didn't see that the middleware is a direct competitor to Datadog's APM.

I'd recommend to state this somewhere that _"the easy way"_ to track exceptions and errors _"is with the APM"_, _"and is integrated as described at \<link to integration docs\>"_.

**Comment by AlJohri** [comment]
@tom-dalton-fanduel can you open up issues on your github fork?

**Comment by tom-dalton-fanduel** [comment]
@AlJohri Yep, done. Didn't realise they weren't enabled by default, sorry! I knew it was too quiet! ;-)

**Comment by AlJohri** [comment]
@avkoval @dhilipsiva would it be possible to remove your packages from PyPi or redirect users to fdjangodog?
